"use client";

import { useState, useEffect, useCallback, useMemo } from "react";
import Image from "next/image";
import Link from "next/link";
import { useRouter, usePathname } from "next/navigation";
import { motion, AnimatePresence } from "framer-motion";
import {
  MapPin, CreditCard, Plus, ChevronRight,
  ShieldCheck, Truck, X, Loader2, Wallet,
  Check, ArrowLeft, Tag,
} from "lucide-react";
import { cn, priceInclusiveOfGst } from "@xelnova/utils";
import { formatCurrency } from "@xelnova/utils";
import { useAuth, ordersApi, usersApi, paymentApi, cartApi, setAccessToken, walletApi } from "@xelnova/api";
import { isAxiosError } from "axios";
import { useCartStore } from "@/lib/store/cart-store";
import { lookupPincode } from "@/lib/store/location-store";
import { INDIAN_STATES } from "@/lib/indian-states";
import { loadRazorpayScript } from "@/lib/load-razorpay";

function hasAuthCookie(): boolean {
  if (typeof document === "undefined") return false;
  return /(?:^|;\s*)xelnova-token=/.test(document.cookie);
}

/** True if the error is an HTTP 401 from the API (stale / invalid session). */
function isUnauthorized(err: unknown): boolean {
  return isAxiosError(err) && err.response?.status === 401;
}

type PaymentChoice = "razorpay" | "wallet";

interface SavedAddress {
  id: string;
  name: string;
  phone: string;
  line1: string;
  line2: string;
  city: string;
  state: string;
  pincode: string;
  type: string;
  /** Personal nickname for `OTHER` addresses (e.g. "Mom's House"). Stored in
   *  the backend `landmark` field for now to avoid a schema change. */
  customLabel?: string;
  isDefault: boolean;
}

const EMPTY_FORM = {
  name: "",
  phone: "",
  line1: "",
  line2: "",
  city: "",
  state: "",
  pincode: "",
  type: "HOME",
  customLabel: "",
};

/** Legacy synthetic placeholder generated by older builds; treat as missing. */
function isPlaceholderEmail(email: string | null | undefined): boolean {
  if (!email) return true;
  return /@phone\.user\.xelnova\.in$/i.test(email.trim());
}

export default function CheckoutPage() {
  const router = useRouter();
  const pathname = usePathname();
  const { user, isAuthenticated, loading: authLoading, updateUser } = useAuth();
  const [mounted, setMounted] = useState(false);
  const [authChecked, setAuthChecked] = useState(false);
  const [addresses, setAddresses] = useState<SavedAddress[]>([]);
  const [selectedAddress, setSelectedAddress] = useState("");
  const [showNewAddress, setShowNewAddress] = useState(true);
  const [form, setForm] = useState(EMPTY_FORM);
  const [formErrors, setFormErrors] = useState<Partial<typeof EMPTY_FORM>>({});
  const [orderPlaced, setOrderPlaced] = useState(false);
  const [orderNumber, setOrderNumber] = useState("");

  // When the order is placed, jump the viewport back to the top so the
  // confirmation card is the first thing the buyer sees instead of being
  // hidden below whatever they'd scrolled past on the checkout form.
  useEffect(() => {
    if (!orderPlaced || typeof window === "undefined") return;
    window.scrollTo({ top: 0, left: 0, behavior: "auto" });
  }, [orderPlaced]);
  const [placingOrder, setPlacingOrder] = useState(false);
  const [orderError, setOrderError] = useState("");
  const [pincodeLooking, setPincodeLooking] = useState(false);
  const items = useCartStore((s) => s.items);
  const totalItems = useCartStore((s) => s.totalItems);
  const clearCart = useCartStore((s) => s.clearCart);
  const [shippingConfig, setShippingConfig] = useState<{ freeShippingMin: number; defaultRate: number }>({ freeShippingMin: 499, defaultRate: 49 });

  const priceTotal = useMemo(
    () =>
      items.reduce(
        (sum, item) =>
          sum + priceInclusiveOfGst(item.price, item.gstRate ?? null) * item.quantity,
        0,
      ),
    [items],
  );
  const compareTotal = useMemo(
    () =>
      items.reduce(
        (sum, item) =>
          sum +
          priceInclusiveOfGst(Math.max(item.price, item.comparePrice), item.gstRate ?? null) *
            item.quantity,
        0,
      ),
    [items],
  );
  const savings = Math.max(0, compareTotal - priceTotal);
  const cartFingerprint = useMemo(
    () => items.map((i) => `${i.productId}:${i.variant ?? ""}:${i.quantity}`).join("|"),
    [items],
  );

  const [pricedFromServer, setPricedFromServer] = useState<{
    subtotal: number;
    discount: number;
    shipping: number;
    tax: number;
    total: number;
  } | null>(null);
  const [couponInput, setCouponInput] = useState("");
  const [couponApplying, setCouponApplying] = useState(false);
  const [appliedCouponCode, setAppliedCouponCode] = useState<string | null>(null);

  const shippingCharge = useMemo(() => {
    if (pricedFromServer) return pricedFromServer.shipping;
    return priceTotal >= shippingConfig.freeShippingMin ? 0 : shippingConfig.defaultRate;
  }, [pricedFromServer, priceTotal, shippingConfig.freeShippingMin, shippingConfig.defaultRate]);

  const discountApplied = pricedFromServer?.discount ?? 0;

  const grandTotal = useMemo(() => {
    if (pricedFromServer) return pricedFromServer.total;
    return priceTotal + shippingCharge;
  }, [pricedFromServer, priceTotal, shippingCharge]);

  const itemCount = totalItems();

  const [paymentChoice, setPaymentChoice] = useState<PaymentChoice>("razorpay");
  const [walletBalance, setWalletBalance] = useState<number | null>(null);
  const [walletLoading, setWalletLoading] = useState(false);
  const [addMoneyAmount, setAddMoneyAmount] = useState("");
  const [addingMoney, setAddingMoney] = useState(false);

  // Contact info captured for phone-only signups (no name/email yet).
  const [contactName, setContactName] = useState("");
  const [contactEmail, setContactEmail] = useState("");
  const [contactErrors, setContactErrors] = useState<{ name?: string; email?: string }>({});

  const needsName = !user?.name?.trim();
  const needsEmail = isPlaceholderEmail(user?.email);
  const showContactBlock = needsName || needsEmail;

  useEffect(() => {
    if (!user) return;
    if (needsName) setContactName((v) => v || (user.name?.trim() ?? ""));
    if (!needsEmail && user.email) setContactEmail((v) => v || user.email!);
  }, [user, needsName, needsEmail]);

  useEffect(() => setMounted(true), []);

  useEffect(() => {
    setAppliedCouponCode(null);
    setPricedFromServer(null);
    setCouponInput("");
  }, [cartFingerprint]);

  useEffect(() => {
    cartApi.getShippingConfig().then(setShippingConfig).catch(() => {});
  }, []);

  useEffect(() => {
    if (!authChecked) return;
    setWalletLoading(true);
    walletApi
      .getCustomerBalance()
      .then((b) => setWalletBalance(b.balance))
      .catch(() => setWalletBalance(0))
      .finally(() => setWalletLoading(false));
  }, [authChecked]);

  useEffect(() => {
    if (authLoading) return;
    if (!isAuthenticated && !hasAuthCookie()) {
      router.replace(`/login?redirect=${encodeURIComponent(pathname)}`);
      return;
    }
    setAuthChecked(true);

    const m = document.cookie.match(/(?:^|;\s*)xelnova-token=([^;]*)/);
    if (m) setAccessToken(decodeURIComponent(m[1]));

    usersApi.getAddresses().then((saved) => {
      if (saved && saved.length > 0) {
        const mapped: SavedAddress[] = saved.map((a) => ({
          id: a.id,
          name: a.fullName,
          phone: a.phone,
          line1: a.addressLine1,
          line2: a.addressLine2 || "",
          city: a.city,
          state: a.state,
          pincode: a.pincode,
          type: a.type,
          customLabel: a.type?.toUpperCase() === "OTHER" ? (a.landmark || undefined) : undefined,
          isDefault: a.isDefault,
        }));
        setAddresses(mapped);
        const def = mapped.find((a) => a.isDefault) || mapped[0];
        setSelectedAddress(def.id);
        setShowNewAddress(false);
      }
    }).catch(() => {});
  }, [authLoading, isAuthenticated, router, pathname]);

  const syncToken = useCallback(() => {
    const m = document.cookie.match(/(?:^|;\s*)xelnova-token=([^;]*)/);
    if (m) setAccessToken(decodeURIComponent(m[1]));
  }, []);

  const syncLocalCartToServer = useCallback(async () => {
    const existing = await cartApi.getCart();
    for (const row of existing.items) {
      await cartApi.removeFromCart(row.productId);
    }
    for (const item of items) {
      await cartApi.addToCart(item.productId, item.quantity, item.variant || undefined);
    }
  }, [items]);

  const handleApplyCoupon = useCallback(async () => {
    const code = couponInput.trim();
    if (!code) return;
    setCouponApplying(true);
    setOrderError("");
    try {
      syncToken();
      const quote = await ordersApi.quoteCheckout({
        items: items.map((i) => ({
          productId: i.productId,
          quantity: i.quantity,
          variant: i.variant,
        })),
        couponCode: code,
      });
      const applied = quote.couponCode || code.toUpperCase();
      setAppliedCouponCode(applied);
      setPricedFromServer({
        subtotal: quote.subtotal,
        discount: quote.discount,
        shipping: quote.shipping,
        tax: quote.tax,
        total: quote.total,
      });
    } catch (e) {
      setAppliedCouponCode(null);
      setPricedFromServer(null);
      setOrderError(e instanceof Error ? e.message : "Could not apply coupon.");
    } finally {
      setCouponApplying(false);
    }
  }, [couponInput, items, syncToken]);

  const clearAppliedCoupon = useCallback(() => {
    setAppliedCouponCode(null);
    setPricedFromServer(null);
    setCouponInput("");
    setOrderError("");
  }, []);

  const openRazorpay = useCallback((paymentOrder: {
    razorpayOrderId: string;
    amount: number;
    currency: string;
    keyId: string;
    orderId: string;
  }, dbOrderNumber: string) => {
    return new Promise<void>((resolve, reject) => {
      void (async () => {
        try {
          await loadRazorpayScript();
        } catch {
          reject(new Error("Payment gateway failed to load. Check your connection and try again."));
          return;
        }
        if (!window.Razorpay) {
          reject(new Error("Payment gateway is loading. Please try again."));
          return;
        }

        const addr = addresses.find((a) => a.id === selectedAddress);
        const options: Record<string, unknown> = {
          key: paymentOrder.keyId,
          amount: paymentOrder.amount,
          currency: paymentOrder.currency,
          name: "Xelnova",
          description: `Order #${dbOrderNumber}`,
          order_id: paymentOrder.razorpayOrderId,
          prefill: {
            name: addr?.name || "",
            contact: addr?.phone || user?.phone || "",
          },
          theme: { color: "#10b981" },
          handler: async (response: { razorpay_order_id: string; razorpay_payment_id: string; razorpay_signature: string }) => {
            try {
              syncToken();
              await paymentApi.verifyPayment({
                razorpay_order_id: response.razorpay_order_id,
                razorpay_payment_id: response.razorpay_payment_id,
                razorpay_signature: response.razorpay_signature,
              });
              resolve();
            } catch (verErr: unknown) {
              const st = isAxiosError(verErr) ? verErr.response?.status : undefined;
              if (st === 400) {
                reject(
                  new Error(
                    "We could not verify this payment with our server. If your bank deducted an amount, it is usually reversed automatically within a few days — or contact support with your order number.",
                  ),
                );
              } else {
                reject(
                  new Error(
                    "Payment verification failed due to a network or server issue. Please retry from your order page — you are not charged until verification succeeds.",
                  ),
                );
              }
            }
          },
          modal: {
            ondismiss: () => {
              reject(
                new Error(
                  "Payment window closed before completion. Your order is saved — open My Orders to retry payment. No charge is completed until you pay successfully.",
                ),
              );
            },
          },
        };

        const rzp = new window.Razorpay(options);
        rzp.on("payment.failed", () => {
          reject(
            new Error(
              "Payment failed or was declined. You have not been charged — try again or use another payment method.",
            ),
          );
        });
        rzp.open();
      })();
    });
  }, [addresses, selectedAddress, syncToken, user?.phone]);

  if (!mounted || !authChecked) {
    return (
      <div className="flex min-h-screen flex-col items-center justify-center gap-3">
        <Loader2 className="h-8 w-8 animate-spin text-primary-600" />
        <p className="text-sm text-text-muted">Loading checkout…</p>
      </div>
    );
  }

  if (orderPlaced) {
    return (
      <div className="relative min-h-screen overflow-hidden bg-gradient-to-br from-primary-50 via-white to-success-50">
        {/* Animated confetti particles */}
        <div className="pointer-events-none absolute inset-0">
          {[...Array(50)].map((_, i) => (
            <motion.div
              key={i}
              initial={{ 
                y: -20, 
                x: Math.random() * (typeof window !== 'undefined' ? window.innerWidth : 1000),
                rotate: 0,
                opacity: 1 
              }}
              animate={{ 
                y: typeof window !== 'undefined' ? window.innerHeight + 100 : 1000,
                rotate: Math.random() * 720 - 360,
                opacity: [1, 1, 0]
              }}
              transition={{ 
                duration: Math.random() * 3 + 2,
                delay: Math.random() * 0.5,
                ease: "linear",
                repeat: Infinity,
                repeatDelay: Math.random() * 2
              }}
              className="absolute h-3 w-3 rounded-sm"
              style={{
                backgroundColor: ['#10b981', '#6366f1', '#f59e0b', '#ec4899', '#3b82f6', '#8b5cf6'][Math.floor(Math.random() * 6)],
                left: `${Math.random() * 100}%`,
              }}
            />
          ))}
        </div>

        {/* Decorative circles */}
        <motion.div 
          initial={{ scale: 0, opacity: 0 }}
          animate={{ scale: 1, opacity: 0.1 }}
          transition={{ duration: 0.8, ease: "easeOut" }}
          className="absolute -top-32 -right-32 h-96 w-96 rounded-full bg-success-500"
        />
        <motion.div 
          initial={{ scale: 0, opacity: 0 }}
          animate={{ scale: 1, opacity: 0.1 }}
          transition={{ duration: 0.8, delay: 0.2, ease: "easeOut" }}
          className="absolute -bottom-32 -left-32 h-80 w-80 rounded-full bg-primary-500"
        />

        <div className="relative flex min-h-screen flex-col items-center justify-center px-4 py-12">
          {/* Success icon with rings */}
          <div className="relative mb-8">
            <motion.div
              initial={{ scale: 0 }}
              animate={{ scale: [0, 1.2, 1] }}
              transition={{ duration: 0.6, times: [0, 0.6, 1] }}
              className="absolute inset-0 rounded-full bg-success-200/50"
              style={{ transform: 'scale(1.8)' }}
            />
            <motion.div
              initial={{ scale: 0 }}
              animate={{ scale: [0, 1.3, 1] }}
              transition={{ duration: 0.6, delay: 0.1, times: [0, 0.6, 1] }}
              className="absolute inset-0 rounded-full bg-success-300/40"
              style={{ transform: 'scale(1.4)' }}
            />
            <motion.div
              initial={{ scale: 0 }}
              animate={{ scale: 1 }}
              transition={{ type: "spring", damping: 12, stiffness: 200, delay: 0.2 }}
              className="relative flex h-28 w-28 items-center justify-center rounded-full bg-gradient-to-br from-success-400 to-success-600 shadow-lg shadow-success-500/30"
            >
              <motion.div
                initial={{ scale: 0, rotate: -180 }}
                animate={{ scale: 1, rotate: 0 }}
                transition={{ type: "spring", damping: 10, stiffness: 150, delay: 0.4 }}
              >
                <Check size={56} className="text-white" strokeWidth={3} />
              </motion.div>
            </motion.div>
          </div>

          {/* Content card */}
          <motion.div 
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.5, duration: 0.5 }}
            className="w-full max-w-md rounded-3xl bg-white/80 backdrop-blur-sm p-8 shadow-xl shadow-gray-200/50 border border-white/50"
          >
            <div className="text-center">
              <motion.h1 
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.6 }}
                className="text-3xl font-bold bg-gradient-to-r from-success-600 to-primary-600 bg-clip-text text-transparent font-display"
              >
                Order Confirmed!
              </motion.h1>
              <motion.p 
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.7 }}
                className="mt-3 text-text-secondary"
              >
                Thank you for your purchase! We&apos;re preparing your order with care.
              </motion.p>
              
              {orderNumber && (
                <motion.div
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  transition={{ delay: 0.8 }}
                  className="mt-6 inline-flex items-center gap-2 rounded-full bg-gradient-to-r from-primary-50 to-success-50 px-5 py-2.5 border border-primary-100"
                >
                  <span className="text-sm text-text-secondary">Order ID:</span>
                  <span className="font-mono font-bold text-primary-700">#{orderNumber}</span>
                </motion.div>
              )}

              {/* Timeline preview */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.9 }}
                className="mt-8 flex justify-center gap-2"
              >
                {[
                  { icon: Check, label: 'Confirmed', active: true },
                  { icon: Truck, label: 'Shipping', active: false },
                  { icon: MapPin, label: 'Delivered', active: false },
                ].map((step, i) => (
                  <div key={i} className="flex items-center">
                    <div className={cn(
                      "flex flex-col items-center",
                      step.active ? "text-success-600" : "text-gray-300"
                    )}>
                      <div className={cn(
                        "flex h-10 w-10 items-center justify-center rounded-full border-2",
                        step.active 
                          ? "border-success-500 bg-success-50" 
                          : "border-gray-200 bg-gray-50"
                      )}>
                        <step.icon size={18} />
                      </div>
                      <span className={cn(
                        "mt-1.5 text-xs font-medium",
                        step.active ? "text-success-700" : "text-gray-400"
                      )}>
                        {step.label}
                      </span>
                    </div>
                    {i < 2 && (
                      <div className={cn(
                        "mx-1 h-0.5 w-8 rounded",
                        i === 0 ? "bg-gradient-to-r from-success-400 to-gray-200" : "bg-gray-200"
                      )} />
                    )}
                  </div>
                ))}
              </motion.div>

              {/* Action buttons */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 1 }}
                className="mt-8 flex flex-col gap-3"
              >
                <Link 
                  href="/account/orders" 
                  className="group relative overflow-hidden rounded-2xl bg-gradient-to-r from-primary-600 to-primary-700 px-6 py-4 text-sm font-semibold text-white shadow-lg shadow-primary-500/25 transition-all hover:shadow-xl hover:shadow-primary-500/30 hover:-translate-y-0.5"
                >
                  <span className="relative z-10 flex items-center justify-center gap-2">
                    <Truck size={18} />
                    Track Your Order
                    <ChevronRight size={16} className="transition-transform group-hover:translate-x-1" />
                  </span>
                  <div className="absolute inset-0 bg-gradient-to-r from-primary-700 to-primary-800 opacity-0 transition-opacity group-hover:opacity-100" />
                </Link>
                <Link 
                  href="/products" 
                  className="flex items-center justify-center gap-2 rounded-2xl border-2 border-gray-200 px-6 py-4 text-sm font-semibold text-text-primary transition-all hover:border-primary-300 hover:bg-primary-50 hover:text-primary-700"
                >
                  Continue Shopping
                  <ArrowLeft size={16} className="rotate-180" />
                </Link>
              </motion.div>

              {/* Additional info */}
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 1.1 }}
                className="mt-8 flex items-center justify-center gap-4 text-xs text-text-muted"
              >
                <div className="flex items-center gap-1.5">
                  <ShieldCheck size={14} className="text-success-500" />
                  <span>Secure Payment</span>
                </div>
                <span className="h-3 w-px bg-gray-200" />
                <div className="flex items-center gap-1.5">
                  <Truck size={14} className="text-primary-500" />
                  <span>Fast Delivery</span>
                </div>
              </motion.div>
            </div>
          </motion.div>

          {/* Celebration message */}
          <motion.p
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 1.2 }}
            className="mt-6 text-sm text-text-muted"
          >
            A confirmation email has been sent to your registered email address.
          </motion.p>
        </div>
      </div>
    );
  }

  if (items.length === 0) {
    return (
      <div className="flex min-h-[70vh] flex-col items-center justify-center px-4 text-center">
        <h1 className="text-2xl font-bold text-text-primary">No items in cart</h1>
        <p className="mt-2 text-text-secondary">Add some items to proceed with checkout.</p>
        <Link href="/products" className="mt-6 rounded-xl bg-primary-600 px-6 py-3 text-sm font-semibold text-white hover:bg-primary-700 transition-colors">Browse Products</Link>
      </div>
    );
  }

  const updateField = async (field: string, value: string) => {
    setForm((prev) => ({ ...prev, [field]: value }));
    setFormErrors((prev) => ({ ...prev, [field]: undefined }));

    // Auto-fill city and state when valid pincode is entered
    if (field === "pincode") {
      const cleanPincode = value.replace(/\D/g, "");
      if (/^[1-9][0-9]{5}$/.test(cleanPincode)) {
        setPincodeLooking(true);
        try {
          const data = await lookupPincode(cleanPincode);
          setForm((prev) => ({
            ...prev,
            city: data.city || prev.city,
            state: data.state || prev.state,
          }));
          setFormErrors((prev) => ({ ...prev, city: undefined, state: undefined, pincode: undefined }));
        } catch {
          // Pincode lookup failed, user can still enter manually
        } finally {
          setPincodeLooking(false);
        }
      }
    }
  };

  const validateForm = () => {
    const errs: Partial<typeof EMPTY_FORM> = {};
    if (!form.name.trim()) errs.name = "Required";
    if (!form.phone.trim() || form.phone.replace(/\D/g, "").length < 10) errs.phone = "Valid phone required";
    if (!form.line1.trim()) errs.line1 = "Required";
    if (!form.city.trim()) errs.city = "Required";
    if (!form.state.trim()) errs.state = "Required";
    if (!form.pincode.trim() || form.pincode.replace(/\D/g, "").length < 6) errs.pincode = "Valid PIN required";
    if (form.type === "OTHER" && !form.customLabel.trim()) {
      errs.customLabel = "Give this address a name (e.g. Mom's House)";
    }
    setFormErrors(errs);
    return Object.keys(errs).length === 0;
  };

  const saveAddress = async () => {
    if (!validateForm()) return;

    const customLabel = form.type === "OTHER" ? form.customLabel.trim() : undefined;
    const localAddr: SavedAddress = {
      id: `addr-${Date.now()}`,
      name: form.name.trim(),
      phone: form.phone.trim(),
      line1: form.line1.trim(),
      line2: form.line2.trim(),
      city: form.city.trim(),
      state: form.state.trim(),
      pincode: form.pincode.trim(),
      type: form.type,
      customLabel,
      isDefault: addresses.length === 0,
    };

    setAddresses((prev) => [...prev, localAddr]);
    setSelectedAddress(localAddr.id);
    setShowNewAddress(false);
    setForm(EMPTY_FORM);
    setFormErrors({});

    try {
      const saved = await usersApi.addAddress({
        fullName: localAddr.name,
        phone: localAddr.phone,
        addressLine1: localAddr.line1,
        addressLine2: localAddr.line2 || null,
        city: localAddr.city,
        district: null,
        state: localAddr.state,
        pincode: localAddr.pincode,
        // Persist the custom nickname for "Other" addresses inside the
        // existing `landmark` field so it survives across sessions without a
        // backend schema change.
        landmark: customLabel || null,
        type: localAddr.type,
      });
      if (saved?.id) {
        setAddresses((prev) =>
          prev.map((a) => (a.id === localAddr.id ? { ...a, id: saved.id } : a))
        );
        setSelectedAddress(saved.id);
      }
    } catch {
      // Address still usable locally even if backend save fails
    }
  };

  const canPay = () => {
    if (!selectedAddress || placingOrder) return false;
    if (paymentChoice === "wallet") {
      if (walletLoading || walletBalance === null) return false;
      if (walletBalance < grandTotal) return false;
    }
    return true;
  };

  const handleAddMoneyToWallet = async () => {
    const amt = Math.floor(Number(addMoneyAmount));
    if (!amt || amt < 10) {
      setOrderError("Enter at least ₹10 to add to wallet.");
      return;
    }
    setAddingMoney(true);
    setOrderError("");
    try {
      syncToken();
      const wm = await walletApi.createAddMoneyOrder(amt);
      await loadRazorpayScript();
      if (!window.Razorpay) throw new Error("Payment gateway is loading. Please try again in a moment.");
      await new Promise<void>((resolve, reject) => {
        const rzp = new window.Razorpay!({
          key: wm.keyId,
          amount: Math.round(wm.amount * 100),
          currency: wm.currency,
          name: "Xelnova Wallet",
          description: `Add ₹${wm.walletCredit} to wallet`,
          order_id: wm.razorpayOrderId,
          theme: { color: "#039855" },
          handler: async (response: {
            razorpay_order_id: string;
            razorpay_payment_id: string;
            razorpay_signature: string;
          }) => {
            try {
              syncToken();
              await walletApi.verifyAddMoney(response);
              const b = await walletApi.getCustomerBalance();
              setWalletBalance(b.balance);
              setAddMoneyAmount("");
              resolve();
            } catch (e) {
              reject(e instanceof Error ? e : new Error("Verification failed"));
            }
          },
          modal: { ondismiss: () => reject(new Error("Payment cancelled")) },
        });
        rzp.on("payment.failed", () => reject(new Error("Payment failed")));
        rzp.open();
      });
    } catch (err) {
      setOrderError(err instanceof Error ? err.message : "Could not add money to wallet.");
    } finally {
      setAddingMoney(false);
    }
  };

  const validateContact = () => {
    if (!showContactBlock) return true;
    const errs: { name?: string; email?: string } = {};
    if (needsName && !contactName.trim()) errs.name = "Please enter your full name";
    if (needsEmail) {
      const e = contactEmail.trim();
      if (!e) errs.email = "Please enter your email";
      else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)) errs.email = "Enter a valid email address";
    }
    setContactErrors(errs);
    return Object.keys(errs).length === 0;
  };

  const placeOrder = async () => {
    const addr = addresses.find((a) => a.id === selectedAddress);
    if (!addr || items.length === 0) return;

    if (!validateContact()) {
      setOrderError("Please complete the contact information.");
      return;
    }

    if (paymentChoice === "wallet") {
      if (walletBalance === null || walletBalance < grandTotal) {
        setOrderError("Insufficient wallet balance. Add money or choose card / UPI.");
        return;
      }
    }

    setPlacingOrder(true);
    setOrderError("");
    syncToken();

    const goToLogin = (msg: string) => {
      setOrderError(msg);
      setTimeout(() => {
        router.replace(`/login?redirect=${encodeURIComponent(pathname)}`);
      }, 1200);
    };

    try {
      if (showContactBlock) {
        const profilePatch: { name?: string; email?: string } = {};
        if (needsName && contactName.trim()) profilePatch.name = contactName.trim();
        if (needsEmail && contactEmail.trim()) profilePatch.email = contactEmail.trim();
        if (Object.keys(profilePatch).length > 0) {
          try {
            const updatedUser = await usersApi.updateProfile(profilePatch);
            updateUser(updatedUser);
          } catch {
            updateUser(profilePatch);
          }
        }
      }

      const order = await ordersApi.createOrder({
        items: items.map((item) => ({
          productId: item.productId,
          quantity: item.quantity,
          variant: item.variant || undefined,
        })),
        shippingAddress: {
          fullName: addr.name,
          phone: addr.phone,
          addressLine1: addr.line1,
          addressLine2: addr.line2 || undefined,
          city: addr.city,
          state: addr.state,
          pincode: addr.pincode,
          type: addr.type,
        },
        paymentMethod: paymentChoice === "wallet" ? "wallet" : "razorpay",
        ...(needsName && contactName.trim() ? { customerName: contactName.trim() } : {}),
        ...(needsEmail && contactEmail.trim() ? { customerEmail: contactEmail.trim() } : {}),
        ...(appliedCouponCode ? { couponCode: appliedCouponCode } : {}),
      });

      if (!order?.id) {
        throw new Error("Order creation failed. Please try again.");
      }

      if (paymentChoice === "wallet") {
        setOrderNumber(order.orderNumber);
        setOrderPlaced(true);
        clearCart();
        return;
      }

      syncToken();
      let paymentOrder;
      try {
        paymentOrder = await paymentApi.createPaymentOrder(order.id);
      } catch (payErr: unknown) {
        const msg = payErr instanceof Error ? payErr.message : "";
        console.error("Payment order creation failed:", payErr);
        if (isUnauthorized(payErr)) {
          goToLogin("Your session has expired. Redirecting to sign in…");
          return;
        }
        if (msg.toLowerCase().includes("not configured")) {
          throw new Error("Payment gateway is not configured. Please contact support.");
        }
        if (msg.toLowerCase().includes("already paid")) {
          throw new Error("This order is already paid. Check your orders page.");
        }
        throw new Error(msg || "Failed to initialize payment. Please try again or contact support.");
      }
      await openRazorpay(paymentOrder, order.orderNumber);

      setOrderNumber(order.orderNumber);
      setOrderPlaced(true);
      clearCart();
    } catch (err) {
      if (isUnauthorized(err)) {
        goToLogin("Your session has expired. Redirecting to sign in…");
        return;
      }
      setOrderError(err instanceof Error ? err.message : "Failed to place order. Please try again.");
    } finally {
      setPlacingOrder(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 pb-[calc(5.5rem+env(safe-area-inset-bottom))] lg:pb-0">
      <div className="mx-auto max-w-5xl px-4 py-6 sm:px-6 sm:py-8 lg:px-8">
        <div className="mb-5 flex flex-wrap items-center gap-2 text-text-secondary sm:mb-6">
          <MapPin size={18} className="shrink-0 text-primary-600" />
          <h1 className="text-lg font-bold text-text-primary">Checkout</h1>
          <span className="hidden text-sm text-text-muted sm:inline">— delivery &amp; payment</span>
        </div>

        <div className="grid gap-6 lg:grid-cols-3 lg:gap-8">
          {/* Left column */}
          <div className="lg:col-span-2">
            <div className="space-y-5">
              {showContactBlock && (
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="rounded-2xl border border-border bg-white p-6 shadow-sm"
                >
                  <h2 className="mb-1 text-lg font-bold text-text-primary">Contact information</h2>
                  <p className="mb-5 text-xs text-text-muted">
                    We&apos;ll send the order confirmation and invoice here. This is saved to your account.
                  </p>
                  <div className="grid gap-3 sm:grid-cols-2">
                    {needsName && (
                      <FormInput
                        label="Full name"
                        value={contactName}
                        error={contactErrors.name}
                        onChange={(v) => {
                          setContactName(v);
                          setContactErrors((p) => ({ ...p, name: undefined }));
                        }}
                        placeholder="John Doe"
                      />
                    )}
                    {needsEmail && (
                      <FormInput
                        label="Email address"
                        value={contactEmail}
                        error={contactErrors.email}
                        onChange={(v) => {
                          setContactEmail(v);
                          setContactErrors((p) => ({ ...p, email: undefined }));
                        }}
                        placeholder="you@example.com"
                      />
                    )}
                  </div>
                </motion.div>
              )}

              <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                className="rounded-2xl border border-border bg-white p-6 shadow-sm"
              >
                  <h2 className="mb-5 text-lg font-bold text-text-primary">Select Delivery Address</h2>

                  {/* Saved addresses */}
                  {addresses.length > 0 && (
                    <div className="space-y-3 mb-4">
                      {addresses.map((addr) => (
                        <label
                          key={addr.id}
                          className={cn(
                            "flex cursor-pointer gap-4 rounded-xl border-2 p-4 transition-all",
                            selectedAddress === addr.id
                              ? "border-primary-500 bg-primary-50"
                              : "border-border hover:border-gray-300"
                          )}
                        >
                          <input
                            type="radio"
                            name="address"
                            checked={selectedAddress === addr.id}
                            onChange={() => setSelectedAddress(addr.id)}
                            className="mt-1 accent-primary-600"
                          />
                          <div className="flex-1">
                            <div className="flex items-center gap-2 flex-wrap">
                              <span className="font-semibold text-text-primary">{addr.name}</span>
                              <span className="rounded bg-gray-100 px-2 py-0.5 text-xs font-medium text-text-secondary capitalize">
                                {addr.type?.toUpperCase() === "OTHER" && addr.customLabel
                                  ? addr.customLabel
                                  : addr.type.toLowerCase()}
                              </span>
                              {addr.isDefault && (
                                <span className="rounded bg-primary-50 px-2 py-0.5 text-xs font-medium text-primary-700">Default</span>
                              )}
                            </div>
                            <p className="mt-1 text-sm text-text-secondary">{addr.line1}{addr.line2 ? `, ${addr.line2}` : ""}</p>
                            <p className="text-sm text-text-secondary">{addr.city}, {addr.state} - {addr.pincode}</p>
                            <p className="mt-1 text-sm text-text-muted">Phone: {addr.phone}</p>
                          </div>
                        </label>
                      ))}
                    </div>
                  )}

                  {/* Add new address toggle */}
                  {!showNewAddress && (
                    <button
                      onClick={() => setShowNewAddress(true)}
                      className="flex items-center gap-2 rounded-xl border-2 border-dashed border-gray-300 px-4 py-3 text-sm font-medium text-text-secondary hover:border-primary-400 hover:text-primary-600 transition-colors w-full justify-center"
                    >
                      <Plus size={16} /> Add New Address
                    </button>
                  )}

                  {/* New address form */}
                  <AnimatePresence>
                    {showNewAddress && (
                      <motion.div
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: "auto", opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        className="overflow-hidden"
                      >
                        <div className="rounded-xl border border-border bg-gray-50 p-5">
                          <div className="flex items-center justify-between mb-4">
                            <h3 className="text-sm font-semibold text-text-primary">New Address</h3>
                            {addresses.length > 0 && (
                              <button onClick={() => setShowNewAddress(false)} className="text-text-muted hover:text-text-primary">
                                <X size={16} />
                              </button>
                            )}
                          </div>
                          <div className="grid gap-3 sm:grid-cols-2">
                            <FormInput label="Full Name" value={form.name} error={formErrors.name} onChange={(v) => updateField("name", v)} placeholder="John Doe" />
                            <FormInput label="Phone Number" value={form.phone} error={formErrors.phone} onChange={(v) => updateField("phone", v)} placeholder="+91 98765 43210" />
                            <div className="sm:col-span-2">
                              <FormInput label="Address Line 1" value={form.line1} error={formErrors.line1} onChange={(v) => updateField("line1", v)} placeholder="House/Flat No., Street" />
                            </div>
                            <div className="sm:col-span-2">
                              <FormInput label="Address Line 2 (Optional)" value={form.line2} onChange={(v) => updateField("line2", v)} placeholder="Landmark, Area" />
                            </div>
                            <div className="relative">
                              <FormInput label="PIN Code" value={form.pincode} error={formErrors.pincode} onChange={(v) => updateField("pincode", v.replace(/\D/g, "").slice(0, 6))} placeholder="400001" />
                              {pincodeLooking && (
                                <div className="absolute right-3 top-7">
                                  <Loader2 size={16} className="animate-spin text-primary-600" />
                                </div>
                              )}
                              <p className="text-[10px] text-text-muted mt-0.5">Enter PIN code to auto-fill city & state</p>
                            </div>
                            <FormInput label="City" value={form.city} error={formErrors.city} onChange={(v) => updateField("city", v)} placeholder="Mumbai" />
                            <div>
                              <label className="block text-xs font-medium text-text-secondary mb-1">State</label>
                              <select
                                value={form.state}
                                onChange={(e) => updateField("state", e.target.value)}
                                className={cn(
                                  "w-full rounded-xl border px-3 py-2.5 text-sm outline-none transition-colors bg-white",
                                  formErrors.state ? "border-danger-500" : "border-gray-200 focus:border-primary-500"
                                )}
                              >
                                <option value="">Select State</option>
                                {INDIAN_STATES.map((s) => (
                                  <option key={s.code} value={s.name}>{s.name}</option>
                                ))}
                              </select>
                              {formErrors.state && <p className="mt-1 text-xs text-danger-600">{formErrors.state}</p>}
                            </div>
                            <div className="flex items-end gap-4 pb-1">
                              {[{ label: "Home", value: "HOME" }, { label: "Office", value: "OFFICE" }, { label: "Other", value: "OTHER" }].map((t) => (
                                <label key={t.value} className="flex items-center gap-2 text-sm text-text-secondary cursor-pointer">
                                  <input
                                    type="radio"
                                    name="addrType"
                                    checked={form.type === t.value}
                                    onChange={() => {
                                      updateField("type", t.value);
                                      if (t.value !== "OTHER") {
                                        // Clear nickname + its error when leaving Other
                                        setForm((prev) => ({ ...prev, customLabel: "" }));
                                        setFormErrors((prev) => ({ ...prev, customLabel: undefined }));
                                      }
                                    }}
                                    className="accent-primary-600"
                                  />
                                  {t.label}
                                </label>
                              ))}
                            </div>
                            {form.type === "OTHER" && (
                              <div className="sm:col-span-2">
                                <FormInput
                                  label="Save as"
                                  value={form.customLabel}
                                  error={formErrors.customLabel}
                                  onChange={(v) => updateField("customLabel", v.slice(0, 30))}
                                  placeholder="e.g. Mom's House, Hostel, Friend's Place"
                                />
                                <p className="text-[10px] text-text-muted mt-0.5">
                                  Give this address a name so you can pick it quickly next time.
                                </p>
                              </div>
                            )}
                            <div className="sm:col-span-2 pt-1">
                              <button
                                onClick={saveAddress}
                                className="rounded-xl bg-primary-600 px-6 py-2.5 text-sm font-semibold text-white hover:bg-primary-700 transition-colors"
                              >
                                Save Address
                              </button>
                            </div>
                          </div>
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
              </motion.div>

              <div className="rounded-2xl border border-border bg-white p-5 shadow-sm">
                    <h3 className="mb-4 text-sm font-bold text-text-primary">Payment method</h3>
                    <div className="space-y-3">
                      <label
                        className={cn(
                          "flex cursor-pointer gap-3 rounded-xl border-2 p-4 transition-all",
                          paymentChoice === "razorpay" ? "border-primary-500 bg-primary-50/50" : "border-border hover:border-gray-300",
                        )}
                      >
                        <input
                          type="radio"
                          name="pay"
                          checked={paymentChoice === "razorpay"}
                          onChange={() => setPaymentChoice("razorpay")}
                          className="mt-1 accent-primary-600"
                        />
                        <div className="flex-1 min-w-0">
                          <p className="text-sm font-semibold text-text-primary">Card / UPI / Net banking</p>
                          <p className="text-xs text-text-muted mt-0.5">Secure checkout powered by Razorpay</p>
                        </div>
                        <CreditCard size={22} className="text-primary-600 shrink-0" />
                      </label>

                      <label
                        className={cn(
                          "flex cursor-pointer gap-3 rounded-xl border-2 p-4 transition-all",
                          paymentChoice === "wallet" ? "border-primary-500 bg-primary-50/50" : "border-border hover:border-gray-300",
                        )}
                      >
                        <input
                          type="radio"
                          name="pay"
                          checked={paymentChoice === "wallet"}
                          onChange={() => setPaymentChoice("wallet")}
                          className="mt-1 accent-primary-600"
                        />
                        <div className="flex-1 min-w-0">
                          <p className="text-sm font-semibold text-text-primary flex items-center gap-2">
                            <Wallet size={16} className="text-primary-600" />
                            Xelnova Wallet
                          </p>
                          <p className="text-xs text-text-muted mt-0.5">
                            {walletLoading
                              ? "Loading balance…"
                              : walletBalance !== null
                                ? `Available: ${formatCurrency(walletBalance)}`
                                : "—"}
                          </p>
                          {paymentChoice === "wallet" && walletBalance !== null && walletBalance < grandTotal && (
                            <p className="text-xs text-amber-800 mt-2 rounded-lg bg-amber-50 border border-amber-200 px-2 py-1.5">
                              Need {formatCurrency(grandTotal - walletBalance)} more. Add money below (Aadhaar KYC required) or choose card / UPI.
                            </p>
                          )}
                        </div>
                      </label>

                      {paymentChoice === "wallet" && (
                        <div className="rounded-xl border border-dashed border-primary-200 bg-gray-50/80 p-4 space-y-3">
                          <p className="text-xs font-medium text-text-primary">Add money to wallet</p>
                          <div className="flex flex-wrap gap-2 items-end">
                            <div className="flex-1 min-w-[120px]">
                              <label className="text-[10px] text-text-muted block mb-1">Amount (₹)</label>
                              <input
                                type="number"
                                min={10}
                                step={1}
                                value={addMoneyAmount}
                                onChange={(e) => setAddMoneyAmount(e.target.value)}
                                placeholder="e.g. 500"
                                className="w-full rounded-lg border border-border bg-white px-3 py-2 text-sm"
                              />
                            </div>
                            <button
                              type="button"
                              onClick={handleAddMoneyToWallet}
                              disabled={addingMoney}
                              className="rounded-lg bg-primary-600 px-4 py-2 text-sm font-semibold text-white hover:bg-primary-700 disabled:opacity-50"
                            >
                              {addingMoney ? "…" : "Add money"}
                            </button>
                          </div>
                          <Link href="/account/wallet" className="text-xs text-primary-600 hover:underline inline-block">
                            Open wallet & KYC settings →
                          </Link>
                        </div>
                      )}
                    </div>
                  </div>

              <div className="rounded-2xl border border-border bg-white p-5 shadow-sm">
                    <h3 className="mb-4 text-sm font-bold text-text-primary">Order Items ({itemCount})</h3>
                    <div className="space-y-3">
                      {items.map((item) => (
                        <div key={item.id} className="flex gap-3">
                          <div className="relative h-16 w-16 shrink-0 overflow-hidden rounded-lg border border-border bg-gray-50">
                            {item.image ? (
                              <Image src={item.image} alt={item.name} fill sizes="64px" className="object-cover" />
                            ) : (
                              <div className="flex h-full w-full items-center justify-center text-text-muted">
                                <Truck size={20} />
                              </div>
                            )}
                          </div>
                          <div className="flex-1 min-w-0">
                            <p className="text-sm font-medium text-text-primary truncate">{item.name}</p>
                            {item.variant && (
                              <p className="text-xs text-text-muted capitalize">{item.variant.replace(/-/g, " / ")}</p>
                            )}
                            <p className="text-xs text-text-muted">Qty: {item.quantity}</p>
                            <p className="text-sm font-semibold text-text-primary">
                              {formatCurrency(
                                priceInclusiveOfGst(item.price, item.gstRate ?? null) * item.quantity,
                              )}
                            </p>
                          </div>
                        </div>
                      ))}
                    </div>
              </div>
            </div>
          </div>

          {/* Right column — Price Details */}
          <div className="lg:col-span-1">
            <div className="sticky top-28 rounded-2xl border border-border bg-white p-5 shadow-sm sm:p-6">
              <h2 className="mb-3 text-lg font-bold text-text-primary">Order Summary</h2>

              <div className="mb-4 space-y-2">
                <label className="text-xs font-medium text-text-secondary">Promo code</label>
                <div className="flex flex-col gap-2 sm:flex-row sm:items-stretch">
                  <input
                    type="text"
                    value={couponInput}
                    onChange={(e) => setCouponInput(e.target.value.toUpperCase())}
                    disabled={!!appliedCouponCode || couponApplying}
                    placeholder="e.g. SAVE10"
                    autoCapitalize="characters"
                    className="min-h-[42px] flex-1 rounded-xl border border-border bg-white px-3 py-2 text-sm text-text-primary outline-none focus:border-primary-500 focus:ring-1 focus:ring-primary-500/30 disabled:bg-gray-50"
                  />
                  {appliedCouponCode ? (
                    <button
                      type="button"
                      onClick={clearAppliedCoupon}
                      className="rounded-xl border border-border px-4 py-2 text-sm font-semibold text-text-primary hover:bg-gray-50 sm:shrink-0"
                    >
                      Remove
                    </button>
                  ) : (
                    <button
                      type="button"
                      onClick={() => void handleApplyCoupon()}
                      disabled={couponApplying || !couponInput.trim()}
                      className="inline-flex min-h-[42px] items-center justify-center rounded-xl bg-primary-600 px-4 py-2 text-sm font-semibold text-white hover:bg-primary-700 disabled:opacity-40 sm:shrink-0"
                    >
                      {couponApplying ? <Loader2 size={16} className="animate-spin" /> : "Apply"}
                    </button>
                  )}
                </div>
                {appliedCouponCode && (
                  <p className="text-xs font-medium text-success-700">
                    Applied <span className="font-mono">{appliedCouponCode}</span>
                  </p>
                )}
              </div>

              {(() => {
                const baseSubtotal = pricedFromServer ? pricedFromServer.subtotal : priceTotal;
                const amountForFreeShipping = shippingConfig.freeShippingMin - baseSubtotal;
                return (
              <div className="space-y-3 text-sm">
                {!pricedFromServer ? (
                  <>
                    <div className="flex justify-between gap-3 text-text-secondary">
                      <span className="min-w-0">Price ({itemCount} {itemCount === 1 ? "item" : "items"})</span>
                      <span className="shrink-0 tabular-nums">{formatCurrency(compareTotal)}</span>
                    </div>
                    {savings > 0 && (
                      <div className="flex justify-between gap-3 text-success-600">
                        <span>Product savings</span>
                        <span className="shrink-0 tabular-nums">-{formatCurrency(savings)}</span>
                      </div>
                    )}
                  </>
                ) : (
                  <div className="flex justify-between gap-3 text-text-secondary">
                    <span className="min-w-0">Items ({itemCount})</span>
                    <span className="shrink-0 tabular-nums">{formatCurrency(pricedFromServer.subtotal)}</span>
                  </div>
                )}
                {pricedFromServer && discountApplied > 0 && (
                  <div className="flex justify-between gap-3 text-success-600">
                    <span className="flex min-w-0 items-center gap-1">
                      <Tag size={14} className="shrink-0" />
                      Coupon ({appliedCouponCode})
                    </span>
                    <span className="shrink-0 tabular-nums">-{formatCurrency(discountApplied)}</span>
                  </div>
                )}
                <div className="flex justify-between gap-3 text-text-secondary">
                  <span>Delivery</span>
                  {shippingCharge === 0 ? (
                    <span className="shrink-0 font-semibold text-success-600">FREE</span>
                  ) : (
                    <span className="shrink-0 tabular-nums">{formatCurrency(shippingCharge)}</span>
                  )}
                </div>
                {!pricedFromServer && shippingCharge > 0 && amountForFreeShipping > 0 && (
                  <p className="text-xs text-text-muted">
                    Add {formatCurrency(amountForFreeShipping)} more for free delivery
                  </p>
                )}
                <hr className="border-border" />
                <div className="flex justify-between gap-3 text-lg font-bold text-text-primary">
                  <span>Total</span>
                  <span className="shrink-0 tabular-nums">{formatCurrency(grandTotal)}</span>
                </div>
                <p className="text-xs text-text-muted">Inclusive of all taxes</p>
                {!pricedFromServer && savings > 0 && (
                  <p className="rounded-xl border border-success-200 bg-success-50 p-2.5 text-center text-sm font-medium text-success-700">
                    You save {formatCurrency(savings)} on product prices
                  </p>
                )}
              </div>
                );
              })()}

              <div className="mt-6 hidden lg:block">
                <button
                  type="button"
                  onClick={() => void placeOrder()}
                  disabled={!canPay()}
                  className={cn(
                    "flex w-full items-center justify-center gap-2 rounded-xl bg-success-600 py-3 text-sm font-bold text-white transition-all hover:bg-success-700",
                    "disabled:cursor-not-allowed disabled:opacity-40",
                  )}
                >
                  {placingOrder ? (
                    <>
                      <Loader2 size={16} className="animate-spin" /> Processing…
                    </>
                  ) : (
                    <>
                      {paymentChoice === "wallet" ? "Pay with wallet" : "Pay Now"}
                      <ChevronRight size={16} />
                    </>
                  )}
                </button>
              </div>

              {orderError && (
                <div className="mt-3 rounded-xl bg-danger-50 border border-danger-200 p-3 text-sm text-danger-700">
                  {orderError}
                </div>
              )}

              <div className="mt-5 space-y-3">
                <p className="text-[10px] font-semibold uppercase tracking-wider text-text-muted">Payments powered by</p>
                <div className="flex flex-wrap items-center gap-2">
                  <div className="inline-flex h-9 w-20 items-center justify-center overflow-hidden rounded-lg border border-border-light bg-white">
                    <Image
                      src="/payments/brands/razorpay.jpeg"
                      alt="Razorpay"
                      width={160}
                      height={72}
                      className="h-full w-full object-contain"
                    />
                  </div>
                  <div className="inline-flex h-9 w-20 items-center justify-center overflow-hidden rounded-lg border border-border-light bg-white">
                    <Image
                      src="/payments/brands/axis.jpeg"
                      alt="Axis Bank"
                      width={160}
                      height={72}
                      className="h-full w-full object-contain"
                    />
                  </div>
                </div>

                <p className="text-[10px] font-semibold uppercase tracking-wider text-text-muted pt-1">We accept</p>
                <div className="flex flex-wrap items-center gap-1.5">
                  {[
                    { name: 'Visa', src: '/payments/brands/visa.jpeg' },
                    { name: 'Mastercard', src: '/payments/brands/master_card.jpeg' },
                    { name: 'Diners Club', src: '/payments/brands/dinners_club.jpeg' },
                    { name: 'Amazon Pay', src: '/payments/brands/amazon_pay.jpeg' },
                    { name: 'Google Pay', src: '/payments/brands/google_pay.jpeg' },
                    { name: 'PhonePe', src: '/payments/brands/phone_pe.jpeg' },
                    { name: 'Paytm', src: '/payments/brands/paytm.jpeg' },
                    { name: 'CRED', src: '/payments/brands/cred.jpeg' },
                    { name: 'PayZapp', src: '/payments/brands/payzapp.jpeg' },
                  ].map((m) => (
                    <span
                      key={m.name}
                      title={m.name}
                      aria-label={m.name}
                      className="inline-flex h-8 w-12 items-center justify-center overflow-hidden rounded border border-border-light bg-white"
                    >
                      <Image
                        src={m.src}
                        alt={m.name}
                        width={96}
                        height={64}
                        className="h-full w-full object-contain"
                      />
                    </span>
                  ))}
                </div>

                <div className="flex items-start gap-2 text-xs text-text-muted pt-1">
                  <ShieldCheck size={14} className="text-success-600 shrink-0 mt-0.5" />
                  <span>Safe and Secure Payments. 100% Authentic.</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="fixed bottom-0 left-0 right-0 z-40 border-t border-border bg-white/95 px-4 py-3 backdrop-blur-md lg:hidden pb-[max(0.75rem,env(safe-area-inset-bottom))] shadow-[0_-4px_24px_rgba(0,0,0,0.06)]">
        <div className="mx-auto flex max-w-lg items-center justify-between gap-3">
          <div className="min-w-0">
            <p className="text-[10px] font-semibold uppercase tracking-wide text-text-muted">Total</p>
            <p className="truncate text-lg font-bold text-text-primary tabular-nums">{formatCurrency(grandTotal)}</p>
          </div>
          <button
            type="button"
            onClick={() => void placeOrder()}
            disabled={!canPay()}
            className={cn(
              "flex min-w-[148px] flex-1 items-center justify-center gap-2 rounded-xl bg-success-600 py-3 text-sm font-bold text-white",
              "disabled:cursor-not-allowed disabled:opacity-40",
            )}
          >
            {placingOrder ? (
              <Loader2 size={16} className="animate-spin" />
            ) : (
              <>
                {paymentChoice === "wallet" ? "Pay" : "Pay Now"}
                <ChevronRight size={16} />
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
}

function FormInput({ label, value, error, onChange, placeholder }: {
  label: string;
  value: string;
  error?: string;
  onChange: (v: string) => void;
  placeholder?: string;
}) {
  return (
    <div>
      <label className="block text-xs font-medium text-text-secondary mb-1">{label}</label>
      <input
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={placeholder}
        className={cn(
          "w-full rounded-xl border bg-white px-4 py-2.5 text-sm text-text-primary outline-none transition-all placeholder:text-text-muted",
          error
            ? "border-danger-400 focus:border-danger-500 focus:ring-1 focus:ring-danger-500/30"
            : "border-border focus:border-primary-500 focus:ring-1 focus:ring-primary-500/30"
        )}
      />
      {error && <p className="mt-1 text-xs text-danger-500">{error}</p>}
    </div>
  );
}

